slowLog.lo: /Users/didi/PhpstormProjects/c/php-src/ext/slowLog/slowLog.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/Users/didi/PhpstormProjects/c/php-src/ext/slowLog $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/didi/PhpstormProjects/c/php-src/ext/slowLog/slowLog.c -o slowLog.lo 
$(phplibdir)/slowLog.la: ./slowLog.la
	$(LIBTOOL) --mode=install cp ./slowLog.la $(phplibdir)

./slowLog.la: $(shared_objects_slowLog) $(SLOWLOG_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_slowLog) $(SLOWLOG_SHARED_LIBADD)

